Repository kookmin-sw/2018-cap1-1, pull requests merged in 2018-05, with the labels that each got.

#65 Truffle init environmet setting
  src/OpenJournal/blockchain/bs-config.json
  src/OpenJournal/blockchain/contracts/EIP20Interface.sol
  src/OpenJournal/blockchain/contracts/JournalToken.sol
  src/OpenJournal/blockchain/contracts/Migrations.sol
  src/OpenJournal/blockchain/migrations/1_initial_migration.js
  src/OpenJournal/blockchain/migrations/2_deploy_contracts.js
  src/OpenJournal/blockchain/package.json
  src/OpenJournal/blockchain/truffle-config.js
  src/OpenJournal/blockchain/truffle.js
Labels: enhancement

#69 Mile stones 2/web frontend/#66
  src/OpenJournal/web/static/css/customize.css
  src/OpenJournal/web/static/gold-medal.png
  src/OpenJournal/web/templates/main_comunity.html
  src/OpenJournal/web/templates/main_comunity_detail.html
Labels: enhancement

#71 make journal view page with viewFunction
  src/OpenJournal/web/static/css/customize.css
  src/OpenJournal/web/static/journal_example.pdf
  src/OpenJournal/web/static/journal_example_first.pdf
  src/OpenJournal/web/static/js/customize.js
  src/OpenJournal/web/templates/main.html
  src/OpenJournal/web/templates/main_comunity_detail.html
  src/OpenJournal/web/templates/main_view_journal.html
Labels: good first issue

#75 contract코드, test코드 추가 및 수정과 .gitignore 수정
  .gitignore
  src/.DS_Store
  src/OpenJournal/blockchain/build/contracts/EIP20Interface.json
  src/OpenJournal/blockchain/build/contracts/JournalToken.json
  src/OpenJournal/blockchain/build/contracts/Migrations.json
  src/OpenJournal/blockchain/build/contracts/OpenJournal.json
  src/OpenJournal/blockchain/build/contracts/SafeMath.json
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
  src/OpenJournal/blockchain/contracts/Owner/Owned.sol
  src/OpenJournal/blockchain/contracts/Token/JournalToken.sol
  src/OpenJournal/blockchain/package-lock.json
  src/OpenJournal/blockchain/test/platform/TestOpenJournal.js
  src/OpenJournal/blockchain/test/token/TestJournalToken.js
Labels: enhancement

#77 Mile stones 2/web backend/#74
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/main.html
  src/OpenJournal/web/templates/main_comunity.html
  src/OpenJournal/web/templates/main_comunity_write.html
  src/OpenJournal/web/templates/main_enroll.html
  src/OpenJournal/web/templates/main_enroll_for_check_journal.html
  src/OpenJournal/web/templates/mongo.html
  src/OpenJournal/web/templates/upload.html
  src/OpenJournal/web/templates/white_board.html
  src/OpenJournal/web/templates/write.html
Labels: enhancement

#80 Mile stones 2/web frontend/#78
  src/OpenJournal/web/static/check.png
  src/OpenJournal/web/static/css/customize.css
  src/OpenJournal/web/static/js/customize.js
  src/OpenJournal/web/static/uncheck.png
  src/OpenJournal/web/templates/main_comunity.html
  src/OpenJournal/web/templates/main_comunity_detail.html
  src/OpenJournal/web/templates/main_enroll_for_check_journal.html
Labels: enhancement

#90 Mile stones 2/web backend/#89
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/enroll.html
  src/OpenJournal/web/templates/login2.html
  src/OpenJournal/web/templates/main.html
  src/OpenJournal/web/templates/main_comunity_detail.html
  src/OpenJournal/web/templates/main_login.html
  src/OpenJournal/web/templates/main_new_member.html
  src/OpenJournal/web/templates/readcookie.html
  src/OpenJournal/web/templates/test.html
  src/OpenJournal/web/templates/white_board.html
Labels: enhancement

#95 Milestones 2/block chain/#73
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
  src/OpenJournal/blockchain/contracts/Token/JournalToken.sol
  src/OpenJournal/blockchain/eth_testdata/geth/LOCK
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/000002.ldb
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/000003.log
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/CURRENT
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/LOCK
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/LOG
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/MANIFEST-000004
  src/OpenJournal/blockchain/eth_testdata/geth/nodekey
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/000002.ldb
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/000003.log
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/CURRENT
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/LOCK
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/LOG
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/MANIFEST-000004
  src/OpenJournal/blockchain/eth_testdata/geth/transactions.rlp
  src/OpenJournal/blockchain/eth_testdata/keystore/UTC--2018-05-09T07-46-17.214548865Z--64bda47c7dea1583d1ad48bfca89842eaa9e6a37
  src/OpenJournal/blockchain/eth_testdata/keystore/UTC--2018-05-09T07-46-26.208128515Z--63517fc37670a17928aa9736a36dfeab1c7dae9a
  src/OpenJournal/blockchain/eth_testdata/testnet/history
  src/OpenJournal/blockchain/test/platform/TestOpenJournal.js
  src/OpenJournal/blockchain/truffle.js
Labels: enhancement

#103 회원권한 검사 및 논문 등록 기능 수정, 코드 깔끔하게 정리
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/main_comunity.html
  src/OpenJournal/web/templates/main_enroll_for_check_journal.html
Labels: enhancement

#110 Milestones 2/block chain/#97
  src/OpenJournal/blockchain/.ethereum/devnet/geth/LOCK
  src/OpenJournal/blockchain/.ethereum/devnet/geth/chaindata/000012.log
  src/OpenJournal/blockchain/.ethereum/devnet/geth/chaindata/000014.ldb
  src/OpenJournal/blockchain/.ethereum/devnet/geth/chaindata/CURRENT
  src/OpenJournal/blockchain/.ethereum/devnet/geth/chaindata/LOCK
  src/OpenJournal/blockchain/.ethereum/devnet/geth/chaindata/LOG
  src/OpenJournal/blockchain/.ethereum/devnet/geth/chaindata/MANIFEST-000013
  src/OpenJournal/blockchain/.ethereum/devnet/geth/nodekey
  src/OpenJournal/blockchain/.ethereum/devnet/geth/transactions.rlp
  src/OpenJournal/blockchain/.ethereum/devnet/history
  src/OpenJournal/blockchain/.ethereum/devnet/keystore/UTC--2018-05-08T09-25-07.670392169Z--6e821e2898e6e8df369bcba05fcec8431e00e5ec
  src/OpenJournal/blockchain/contracts/Owner/Owned.sol
  src/OpenJournal/blockchain/eth_testdata/geth/LOCK
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/000002.ldb
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/000003.log
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/CURRENT
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/LOCK
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/LOG
  src/OpenJournal/blockchain/eth_testdata/geth/chaindata/MANIFEST-000004
  src/OpenJournal/blockchain/eth_testdata/geth/nodekey
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/000002.ldb
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/000003.log
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/CURRENT
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/LOCK
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/LOG
  src/OpenJournal/blockchain/eth_testdata/geth/nodes/MANIFEST-000004
  src/OpenJournal/blockchain/eth_testdata/geth/transactions.rlp
  src/OpenJournal/blockchain/eth_testdata/keystore/UTC--2018-05-09T07-46-17.214548865Z--64bda47c7dea1583d1ad48bfca89842eaa9e6a37
  src/OpenJournal/blockchain/eth_testdata/keystore/UTC--2018-05-09T07-46-26.208128515Z--63517fc37670a17928aa9736a36dfeab1c7dae9a
  src/OpenJournal/blockchain/eth_testdata/testnet/history
  src/OpenJournal/blockchain/src/js/app.js
Labels: enhancement

#115 논문 저자와 가격 Get함수
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
  src/OpenJournal/blockchain/test/platform/TestOpenJournal.js
  src/OpenJournal/blockchain/truffle.js
Labels: enhancement

#121 Adding reference journal hash number list
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
  src/OpenJournal/blockchain/test/platform/TestOpenJournal.js
  src/OpenJournal/blockchain/truffle.js
Labels: good first issue

#122 Mile stones 2/web backend/#119
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/main_comunity_detail.html
  src/OpenJournal/web/templates/main_enroll.html
  src/OpenJournal/web/templates/main_mypage.html
  src/OpenJournal/web/templates/main_view_journal.html
Labels: enhancement

#124 OpenJournal Template and Example pdf file
  doc/Template/Example.docx
  doc/Template/Example.pdf
  doc/Template/OpenJournal Template.docx
Labels: good first issue

#127 Parsing references journal information from PDF file
  src/OpenJournal/web/PDFparser.py
Labels: good first issue

#131 업로한 논문 pdf뷰 기능 구현
  src/OpenJournal/web/route.py
  src/OpenJournal/web/static/CG_Objects_2018.pdf
  src/OpenJournal/web/static/journal/05.CG_VertexProcessor_2018.pdf
  src/OpenJournal/web/static/journal/06.CG_Clipping_Rasterization_2018.pdf
  src/OpenJournal/web/static/journal/07.CG_Shading_2018.pdf
  src/OpenJournal/web/static/journal/CG_Objects_2018.pdf
  src/OpenJournal/web/templates/main_view_journal.html
Labels: enhancement

#133 Milestones 2/web frontend block chain/#129
  src/OpenJournal/blockchain/src/index.html
  src/OpenJournal/blockchain/src/js/app.js
  src/OpenJournal/blockchain/src/js/finalenroll.js
  src/OpenJournal/blockchain/src/main_view_my_journal.html
Labels: enhancement

#130 Adding reference journal hash string
  src/OpenJournal/web/PDFparser.py
Labels: enhancement

#138 파일업로드 경로 변경, 몽고디비 컬렉션 추가
  src/OpenJournal/web/route.py
  src/OpenJournal/web/route.pyc
  src/OpenJournal/web/static/journal/03.CG_Objects_2018.pdf
  src/OpenJournal/web/web.ini
Labels: enhancement

#141 버전 업데이트 기능 수정 및 최종 등록 기능 구현1
  src/OpenJournal/web/route.py
  src/OpenJournal/web/static/journal/04.CG_Transformations_2018.pdf
  src/OpenJournal/web/templates/main_enroll.html
  src/OpenJournal/web/templates/main_final_paper_enroll.html
  src/OpenJournal/web/templates/main_view_fix_journal.html
  src/OpenJournal/web/templates/main_view_journal.html
  src/OpenJournal/web/templates/main_view_my_journal.html
Labels: enhancement

#144 Reference 논문에게 보상주기
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
  src/OpenJournal/blockchain/contracts/Token/EIP20Interface.sol
  src/OpenJournal/blockchain/contracts/Token/JournalToken.sol
  src/OpenJournal/blockchain/migrations/2_deploy_contracts.js
  src/OpenJournal/blockchain/test/platform/TestOpenJournal.js
  src/OpenJournal/blockchain/test/token/TestJournalToken.js
  src/OpenJournal/blockchain/truffle.js
Labels: enhancement

#146 Adding get user's registList and subscribeList
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
  src/OpenJournal/blockchain/test/platform/TestOpenJournal.js
Labels: enhancement

#148 Merging route.py and PDFparser.py and modifying some errors
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/main_view_journal.html
Labels: enhancement

#150 Mile stones 3/web backend/#140
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/main_view_journal.html
Labels: enhancement

#153 Delete PDFparser.py
  src/OpenJournal/web/PDFparser.py
Labels: enhancement

#155 Get journal title from journal number
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
Labels: enhancement

#156 Mile stone 3/web frontend block chain/#142
  src/OpenJournal/blockchain/src/index.html
  src/OpenJournal/blockchain/src/js/app.js
  src/OpenJournal/blockchain/src/js/finalenroll.js
  src/OpenJournal/blockchain/src/main_view_journal.html
  src/OpenJournal/web/static/js/customize.js
  src/OpenJournal/web/templates/main_view_journal.html
Labels: enhancement

#158 논문번호,제목 파싱과 WebFrontend 연동
  src/OpenJournal/web/route.py
  src/OpenJournal/web/static/journal/Example.pdf
  src/OpenJournal/web/templates/main_view_journal.html
Labels: enhancement

#159 Adding get is_subscribed mapping data
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
Labels: enhancement

#167 Mile stones 3/web backend/#166
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/main_login.html
  src/OpenJournal/web/templates/main_view_fix_journal.html
Labels: enhancement

#171 token rate 설정 및 buyToken, sellToken function 구현
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
  src/OpenJournal/blockchain/contracts/Token/JournalToken.sol
  src/OpenJournal/blockchain/test/token/TestJournalToken.js
  src/OpenJournal/web/config/__init__.py
  src/OpenJournal/web/route.py
Labels: enhancement

#173 Delete miniToken concept
  src/OpenJournal/blockchain/contracts/OpenJournal.sol
  src/OpenJournal/blockchain/contracts/Token/JournalToken.sol
  src/OpenJournal/blockchain/test/platform/TestOpenJournal.js
  src/OpenJournal/blockchain/test/token/TestJournalToken.js
Labels: enhancement

#179 구글 계정 로그인 시 일반회원과 동일한 기능 적용 코드 수정
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/main.html
  src/OpenJournal/web/templates/main_login.html
  src/OpenJournal/web/templates/main_new_member.html
Labels: enhancement

#186 Milestones 3/merge/#185
  src/build/contracts/EIP20Interface.json
  src/build/contracts/JournalToken.json
  src/build/contracts/Migrations.json
  src/build/contracts/OpenJournal.json
  src/build/contracts/Owned.json
  src/build/contracts/SafeMath.json
  src/contracts/OpenJournal.sol
  src/test/platform/TestOpenJournal.js
Labels: enhancement

#187 Mile stones 3/web frontend/#183
  src/src/main_token_buy_page.html
  src/src/main_view_journal.html
  src/src/static/js/customize.js
Labels: bug, enhancement

#188 Milestones 3/merge/#185
  .gitignore
  doc/졸프 전시회 시나리오.pdf
  src/.vscode/settings.json
  src/build/contracts/EIP20Interface.json
  src/build/contracts/JournalToken.json
  src/build/contracts/Migrations.json
  src/build/contracts/OpenJournal.json
  src/build/contracts/Owned.json
  src/build/contracts/SafeMath.json
  src/contracts/OpenJournal.sol
  src/src/.route.py.swp
  src/src/config/__init__.py
  src/src/config/__init__.pyc
  src/src/main_login.html
  src/src/main_new_member.html
  src/src/route.py
  src/src/static/journal/06.CG_Clipping_Rasterization_2018.pdf
  src/src/static/journal/07.CG_Shading_2018.pdf
  src/src/static/journal/Example.pdf
  src/src/static/journal/Transformations.pdf
  src/src/static/js/common.js
  src/src/static/js/finalenroll.js
  src/src/static/js/subscribemanage.js
  src/src/static/js/temp.js
  src/test/platform/TestOpenJournal.js
Labels: enhancement

#193 flask static folder structure change
  src/src/config/__init__.pyc
  src/src/css/bootstrap.min.css
  src/src/css/bootstrap.min.css.map
  src/src/css/customize.css
  src/src/css/main.css
  src/src/css/materialize.css
  src/src/css/materialize.min.css
  src/src/css/style.css
  src/src/img/background1.jpg
  src/src/img/background2.jpg
  src/src/img/background3.jpg
  src/src/img/background_subscribe.jpg
  src/src/img/buyimage.jpg
  src/src/img/check.png
  src/src/img/comunity.jpg
  src/src/img/enrollment.png
  src/src/img/gold-medal.png
  src/src/img/journal_example.pdf
  src/src/img/journal_example_first.pdf
  src/src/img/uncheck.png
  src/src/journal/Example.pdf
  src/src/journal/Example7.pdf
  src/src/journal/Sample2.pdf
  src/src/js/app_test.js
  src/src/js/app_test2.js
  src/src/js/bootstrap.min.js
  src/src/js/common.js
  src/src/js/customize.js
  src/src/js/finalenroll.js
  src/src/js/init.js
  src/src/js/loadmypage.js
  src/src/js/materialize.js
  src/src/js/materialize.min.js
  src/src/js/subscribemanage.js
  src/src/js/temp.js
  src/src/js/truffle-contract.js
  src/src/js/web3.min.js
  src/src/js/web3newmember.js
  src/src/main.html
  src/src/main_comunity.html
  src/src/main_comunity_detail.html
  src/src/main_comunity_write.html
  src/src/main_enroll.html
  src/src/main_enroll_for_check_journal.html
  src/src/main_journal_update.html
  src/src/main_login.html
  src/src/main_mypage.html
  src/src/main_new_member.html
  src/src/main_token_buy_page.html
  src/src/main_view_fix_journal.html
  src/src/main_view_journal.html
  src/src/route.py
  src/src/route.pyc
  src/src/wsgi.pyc
Labels: enhancement

#196 find bug about google login button
  src/src/img/sign-in-with-google.png
  src/src/main.html
  src/src/main_login.html
Labels: bug

#198 Mile stones 3/web frontend/#197
  src/src/main_login.html
  src/src/main_token_buy_page.html
Labels: bug

#199 Mile stones 3/merge/#194
  src/build/contracts/EIP20Interface.json
  src/build/contracts/JournalToken.json
  src/build/contracts/Migrations.json
  src/build/contracts/OpenJournal.json
  src/build/contracts/Owned.json
  src/build/contracts/SafeMath.json
  src/src/OpenJournal.json
  src/src/config/__init__.py
  src/src/config/__init__.pyc
  src/src/js/common.js
  src/src/js/customize.js
  src/src/js/finalenroll.js
  src/src/main_view_journal.html
  src/src/route.py
  src/src/route.pyc
  src/src/wsgi.pyc
Labels: enhancement

#204 make draft main.html
  src/src/main.html
Labels: enhancement

#206 make loading page during enroll member
  src/src/css/materialize.css
  src/src/img/github-logo.png
  src/src/img/newmember.jpg
  src/src/main_waitView.html
Labels: good first issue

#212 Add footer in all of html page
  src/src/.main.html.swp
  src/src/.test.py.swp
  src/src/main.html
  src/src/main_comunity.html
  src/src/main_comunity_detail.html
  src/src/main_comunity_write.html
  src/src/main_enroll.html
  src/src/main_enroll_for_check_journal.html
  src/src/main_journal_update.html
  src/src/main_mypage.html
  src/src/main_new_member.html
  src/src/main_search_paper.html
  src/src/main_token_buy_page.html
  src/src/main_view_fix_journal.html
  src/src/main_view_journal.html
  src/src/main_waitView.html
Labels: enhancement

#213 Defence abusing about distributing token percent
  src/src/js/finalenroll.js
  src/src/js/materialize.js
  src/src/main_view_journal.html
Labels: enhancement

#214 Mile stones 3/merge/#209
  src/src/js/.common.js.swp
  src/src/js/common.js
  src/src/js/signuploading.js
  src/src/js/web3newmember.js
  src/src/main.html
  src/src/main_comunity.html
  src/src/main_comunity_detail.html
  src/src/main_comunity_write.html
  src/src/main_enroll.html
  src/src/main_journal_update.html
  src/src/main_mypage.html
  src/src/main_new_member.html
  src/src/main_search_paper.html
  src/src/main_token_buy_page.html
  src/src/main_view_fix_journal.html
  src/src/main_view_journal.html
  src/src/main_waitView.html
  src/src/route.py
Labels: enhancement

#218 Contributor에게 보상이 돌아가는 logic을 html에 적용
  src/build/contracts/EIP20Interface.json
  src/build/contracts/JournalToken.json
  src/build/contracts/OpenJournal.json
  src/build/contracts/Owned.json
  src/build/contracts/SafeMath.json
  src/contracts/OpenJournal.sol
  src/src/journal/Sample11.pdf
  src/src/main_view_journal.html
  src/src/route.py
Labels: enhancement

#223 Complete Subscribing merge
  src/src/journal/11Vol96No2.pdf
  src/src/journal/2018_ver_2.3_1.pdf
  src/src/js/common.js
  src/src/js/subscribemanage.js
  src/src/main_view_fix_journal.html
  src/src/main_view_journal.html
  src/src/route.py
Labels: enhancement

#229 fix bug
  src/src/js/common.js
  src/src/main_comunity.html
  src/src/main_comunity_detail.html
  src/src/main_comunity_write.html
  src/src/main_enroll.html
  src/src/main_enroll_for_check_journal.html
  src/src/main_journal_update.html
  src/src/main_login.html
  src/src/main_mypage.html
  src/src/main_new_member.html
  src/src/main_oauth_enroll.html
  src/src/main_token_buy_page.html
  src/src/main_view_fix_journal.html
Labels: bug, enhancement

#230 Mile stones 3/block chainand web backend/#224
  src/src/js/loadmypage.js
  src/src/main_mypage.html
  src/src/main_view_journal.html
  src/src/route.py
Labels: enhancement

#233 Mile stones 3/block chain/#225
  src/src/js/tokenexchange.js
  src/src/main_token_buy_page.html
Labels: enhancement

#234 Mile stones 3/web frontend/#231
  src/src/img/main1.png
  src/src/main.html
Labels: enhancement

#236 Mile stones 3/all/#227
  src/build/contracts/EIP20Interface.json
  src/build/contracts/JournalToken.json
  src/build/contracts/Migrations.json
  src/build/contracts/OpenJournal.json
  src/build/contracts/Owned.json
  src/build/contracts/SafeMath.json
  src/contracts/OpenJournal.sol
  src/migrations/2_deploy_contract.js
  src/src/.main_view_fix_journal.html.swp
  src/src/OpenJournal.json
  src/src/journal/Sample12.pdf
  src/src/journal/Sample5.pdf
  src/src/journal/Sample9.pdf
  src/src/js/.finalenroll.js.swp
  src/src/js/finalenroll.js
  src/src/js/loadmypage.js
  src/src/main_enroll.html
  src/src/main_mypage.html
  src/src/main_view_fix_journal.html
  src/src/main_view_journal.html
  src/src/route.py
Labels: enhancement

#239 Mile stones 3/web frontend/#235
  src/src/doc/template.docx
  src/src/main.html
  src/src/main_comunity.html
  src/src/main_enroll.html
  src/src/main_token_buy_page.html
  src/src/main_view_fix_journal.html
Labels: bug

#242 Mile stones 3/web frontend/#240
  src/src/main_enroll.html
  src/src/main_view_fix_journal.html
  src/src/main_view_fix_journal.html.save
  src/src/main_view_journal.html
Labels: bug, enhancement

#243 Mile stones 3/web frontend/#240
  src/src/img/gold-medal.png
  src/src/img/medal-bronze.png
  src/src/img/medal-gold.png
  src/src/img/medal-silver.png
  src/src/img/medal-star.png
  src/src/main_comunity_detail.html
  src/src/route.py
Labels: bug

#245 검수 논문 삭제 버튼 구현, 논문 댓글 채택 기능 수정
  src/src/journal/Sample7.pdf
  src/src/main_view_journal.html
  src/src/route.py
Labels: enhancement

#249 Mile stones 3/frontend backend/#248
  src/src/js/.signuploading.js.swp
  src/src/js/signuploading.js
  src/src/main_view_journal.html
  src/src/route.py
Labels: enhancement

#250 Mile stones 3/web frontend block chain/#244
  src/src/route.py
Labels: enhancement

#251 Mile stones 3/all/#246
  src/src/css/customize.css
  src/src/img/background_transaction.jpg
  src/src/js/app_test.js
  src/src/js/app_test2.js
  src/src/js/common.js
  src/src/js/finalenroll.js
  src/src/js/loadmypage.js
  src/src/js/signuploading.js
  src/src/js/subscribemanage.js
  src/src/js/tokenexchange.js
  src/src/js/web3newmember.js
  src/src/main_comunity.html
  src/src/main_mypage.html
  src/src/main_token_buy_page.html
  src/src/main_view_transaction.html
Labels: enhancement
