Repository kookmin-sw/2018-cap1-1, pull requests merged in 2018-04, with the labels that each got.

#24 Mile stones 1/block chain/#23
  src/.DS_Store
  src/OpenJournal/blockchain/.DS_Store
  src/OpenJournal/blockchain/Cha_Practice/Chapter2.pdf
  src/OpenJournal/blockchain/Cha_Practice/Chapter3.pdf
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/AddressSample.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/ArraySample.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/DataTypeSample.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/HelloWorldOrg.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/Inheritance.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/IntSample.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/MappingSample.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/RecvEther.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/SelfDestructSample.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter3/StructSample.sol
Labels: Study Content

#31 Web Backend Oauth를 이용한 로그인 및 세션기능 구현
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/about.html
  src/OpenJournal/web/templates/authorization.html
  src/OpenJournal/web/templates/home.html
  src/OpenJournal/web/templates/index.html
  src/OpenJournal/web/templates/layout.html
  src/OpenJournal/web/templates/login2.html
  src/OpenJournal/web/templates/mongo.html
  src/OpenJournal/web/templates/readcookie.html
Labels: enhancement

#35 web3.js를 이용한 간단한 예제 제작
  src/OpenJournal/blockchain/Eom_Practice/Chap04/Chapter4_Study_Material.docx
  src/OpenJournal/blockchain/Eom_Practice/Chap04/Chapter4_Study_Material.pdf
  src/OpenJournal/blockchain/Eom_Practice/Chap04/SampleCode/Final/app.js
  src/OpenJournal/blockchain/Eom_Practice/Chap04/SampleCode/Final/package.json
  src/OpenJournal/blockchain/Eom_Practice/Chap04/SampleCode/Final/public/css/bootstrap.min.css
  src/OpenJournal/blockchain/Eom_Practice/Chap04/SampleCode/Final/public/html/index.html
  src/OpenJournal/blockchain/Eom_Practice/Chap04/SampleCode/Final/public/js/jquery.min.js
  src/OpenJournal/blockchain/Eom_Practice/Chap04/SampleCode/Final/public/js/main.js
  src/OpenJournal/blockchain/Eom_Practice/Chap04/SampleCode/Final/public/js/sha1.min.js
  src/OpenJournal/blockchain/Eom_Practice/Chap04/SampleCode/Final/public/js/socket.io.min.js
  src/OpenJournal/blockchain/Eom_Practice/Chap04/~$apter4_Study_Material.docx
Labels: Study Content

#37 Chapter5 4월 7일까지 공부한 내용
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter5/KeyValueStore.bin
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter5/KeyValueStore.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter5/PersonCertification.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter5/TransactionLogBUG.sol
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter5/TransactionLogNoBUG.bin
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter5/TransactionLogNoBug.sol
Labels: Study Content

#41 API Reference 내용
  src/OpenJournal/blockchain/Cha_Practice/API 레퍼런스.pdf
  src/OpenJournal/blockchain/Cha_Practice/Chapter5.pdf
  src/OpenJournal/blockchain/Cha_Practice/소스코드/Chapter5/PersonCertification.bin
Labels: Study Content

#46 2018-04-10 Minjun : complete category menu and close branch
  src/OpenJournal/web/static/js/customize.js
  src/OpenJournal/web/templates/index.html
Labels: enhancement

#48 Mile stones 1/web frontend/#05
  src/OpenJournal/web/static/css/materialize.css
  src/OpenJournal/web/templates/index.html
Labels: enhancement

#47 web backend/#45 Implement membership function
  src/OpenJournal/web/geckodriver.log
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/enroll.html
Labels: enhancement

#52 Mile stones 2/web fronted/#51
  src/OpenJournal/web/static/css/materialize.css
  src/OpenJournal/web/static/enrollment.png
  src/OpenJournal/web/templates/index.html
  src/OpenJournal/web/templates/main.html
  src/OpenJournal/web/templates/sub_enroll.html
Labels: enhancement

#54 make draft that enroll for journal check page
  src/OpenJournal/web/static/css/materialize.css
  src/OpenJournal/web/static/js/customize.js
  src/OpenJournal/web/templates/main.html
  src/OpenJournal/web/templates/main_enroll.html
  src/OpenJournal/web/templates/main_enroll_for_check_journal.html
Labels: good first issue

#57 make a new page about cominuty page
  src/OpenJournal/web/static/comunity.jpg
  src/OpenJournal/web/templates/main.html
  src/OpenJournal/web/templates/main_comunity.html
  src/OpenJournal/web/templates/main_enroll.html
  src/OpenJournal/web/templates/main_enroll_for_check_journal.html
Labels: good first issue

#58 Mile stones 2/web backend/#55
  src/OpenJournal/web/route.py
  src/OpenJournal/web/templates/main_enroll.html
  src/OpenJournal/web/templates/upload.html
Labels: enhancement

#62 make new page about writing comunity contents
  src/OpenJournal/web/static/css/customize.css
  src/OpenJournal/web/static/css/materialize.css
  src/OpenJournal/web/templates/main_comunity.html
  src/OpenJournal/web/templates/main_comunity_write.html
Labels: good first issue
